import AppKit
import UniformTypeIdentifiers

enum ClipboardCaptureReader {
    static let sensitiveTypes = Set([
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ])

    static func containsSensitiveMarker(_ pasteboard: NSPasteboard) -> Bool {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        return !types.isDisjoint(with: sensitiveTypes)
    }

    static func capture(
        from pasteboard: NSPasteboard,
        sourceApplication: NSRunningApplication?
    ) -> ClipboardCapture? {
        guard !containsSensitiveMarker(pasteboard) else {
            return nil
        }

        let sourceName = sourceApplication?.localizedName ?? "Unknown App"
        let sourceBundleIdentifier = sourceApplication?.bundleIdentifier

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let references = urls.map(ClipboardFileReference.init)
            let title = references.count == 1
                ? references[0].displayName
                : "\(references.count) files"
            let subtitle = references.count == 1
                ? URL(fileURLWithPath: references[0].lastKnownPath)
                    .deletingLastPathComponent().path
                : "Multiple file paths"
            return ClipboardCapture(
                kind: .file,
                title: title,
                subtitle: subtitle,
                sourceAppName: sourceName,
                sourceBundleIdentifier: sourceBundleIdentifier,
                payload: .files(references),
                signature: ClipboardCapture.signature(
                    kind: .file,
                    representations: references.map {
                        ("public.file-url", Data($0.lastKnownPath.utf8))
                    }
                ),
                searchText: references.map(\.lastKnownPath).joined(separator: "\n")
            )
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let rtfData = pasteboard.data(forType: .rtf)
            let rtfdData = pasteboard.data(forType: .rtfd)
            let htmlData = pasteboard.data(forType: .html)
            var representations = [("public.utf8-plain-text", Data(text.utf8))]
            if let rtfData {
                representations.append(("public.rtf", rtfData))
            }
            if let rtfdData {
                representations.append(("com.apple.rtfd", rtfdData))
            }
            if let htmlData {
                representations.append(("public.html", htmlData))
            }

            return ClipboardCapture(
                kind: .text,
                title: text.singleLinePreview(limit: 80),
                subtitle: "\(text.count) characters",
                sourceAppName: sourceName,
                sourceBundleIdentifier: sourceBundleIdentifier,
                payload: .text(
                    plainText: text,
                    rtfData: rtfData,
                    rtfdData: rtfdData,
                    htmlData: htmlData
                ),
                signature: ClipboardCapture.signature(
                    kind: .text,
                    representations: representations
                ),
                searchText: text
            )
        }

        if let imageCapture = imageCapture(
            from: pasteboard,
            sourceName: sourceName,
            sourceBundleIdentifier: sourceBundleIdentifier
        ) {
            return imageCapture
        }

        return nil
    }

    static func screenshot(url: URL) -> ClipboardCapture? {
        guard
            let image = NSImage(contentsOf: url),
            let pngData = image.pngData
        else {
            return nil
        }

        return ClipboardCapture(
            kind: .screenshot,
            title: url.lastPathComponent,
            subtitle: "Screenshot - \(Int(image.size.width)) x \(Int(image.size.height))",
            sourceAppName: "Screenshot",
            sourceBundleIdentifier: "com.apple.screencaptureui",
            payload: .image(
                data: pngData,
                typeIdentifier: UTType.png.identifier,
                screenshotOriginalPath: url.path
            ),
            signature: ClipboardCapture.signature(
                kind: .screenshot,
                representations: [(UTType.png.identifier, pngData)]
            ),
            searchText: url.lastPathComponent
        )
    }

    private static func imageCapture(
        from pasteboard: NSPasteboard,
        sourceName: String,
        sourceBundleIdentifier: String?
    ) -> ClipboardCapture? {
        let imageData: Data
        let typeIdentifier: String

        if let pngData = pasteboard.data(forType: .png) {
            imageData = pngData
            typeIdentifier = UTType.png.identifier
        } else if
            let tiffData = pasteboard.data(forType: .tiff),
            let image = NSImage(data: tiffData),
            let pngData = image.pngData
        {
            imageData = pngData
            typeIdentifier = UTType.png.identifier
        } else {
            return nil
        }

        let image = NSImage(data: imageData)
        let width = Int(image?.size.width ?? 0)
        let height = Int(image?.size.height ?? 0)
        return ClipboardCapture(
            kind: .image,
            title: "Image",
            subtitle: "\(width) x \(height)",
            sourceAppName: sourceName,
            sourceBundleIdentifier: sourceBundleIdentifier,
            payload: .image(data: imageData, typeIdentifier: typeIdentifier),
            signature: ClipboardCapture.signature(
                kind: .image,
                representations: [(typeIdentifier, imageData)]
            ),
            searchText: ""
        )
    }
}

extension NSImage {
    var pngData: Data? {
        guard
            let tiffRepresentation,
            let bitmap = NSBitmapImageRep(data: tiffRepresentation)
        else {
            return nil
        }

        return bitmap.representation(using: .png, properties: [:])
    }
}
